export const OPERATIONS = ['+', '-', '*', '÷', '%'];
export const EQUAL_SIGN = '=';
export const CHANGE_SIGN = '+/-';
export const CLEAR_SIGN = 'AC';
export const PLUS_SIGN = '+';
export const MINUS_SIGN = '-';
export const MULTIPLY_SIGN = '*';
export const DIVIDE_SIGN = '÷';
export const PERCENTAGE_SIGN = '%';
export const DOT_SIGN = '.';
